"""add inference output fields

Revision ID: 2b2a39af36dc
Revises: fcc54c501383
Create Date: 2026-02-22 00:24:02.982688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2a39af36dc'
down_revision: Union[str, Sequence[str], None] = 'fcc54c501383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_inference', sa.Column('sentiment', sa.String(length=32), nullable=True))
    op.add_column('document_inference', sa.Column('emotion_labels', sa.JSON(), nullable=True))
    op.add_column('document_inference', sa.Column('calibrated_confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_document_inference_sentiment'), 'document_inference', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_inference_sentiment'), table_name='document_inference')
    op.drop_column('document_inference', 'calibrated_confidence')
    op.drop_column('document_inference', 'emotion_labels')
    op.drop_column('document_inference', 'sentiment')
    # ### end Alembic commands ###
