"""add alert rules and evidence

Revision ID: 6c884d5b8ae8
Revises: e4ce2024e449
Create Date: 2026-02-22 01:12:23.034023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c884d5b8ae8'
down_revision: Union[str, Sequence[str], None] = 'e4ce2024e449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=True)
    op.create_table('alert_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('emotion_match', sa.String(length=64), nullable=True),
    sa.Column('keyword_hits', sa.JSON(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'document_id', name='uq_alert_evidence_alert_document')
    )
    op.create_index('ix_alert_evidence_alert_contrib', 'alert_evidence', ['alert_id', 'contribution'], unique=False)
    op.create_index(op.f('ix_alert_evidence_alert_id'), 'alert_evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_evidence_document_id'), 'alert_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_alert_evidence_emotion_match'), 'alert_evidence', ['emotion_match'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_evidence_emotion_match'), table_name='alert_evidence')
    op.drop_index(op.f('ix_alert_evidence_document_id'), table_name='alert_evidence')
    op.drop_index(op.f('ix_alert_evidence_alert_id'), table_name='alert_evidence')
    op.drop_index('ix_alert_evidence_alert_contrib', table_name='alert_evidence')
    op.drop_table('alert_evidence')
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
