"""add topics tables

Revision ID: b32eb3b5e1ce
Revises: fc460caa15a2
Create Date: 2026-02-22 00:54:16.555610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32eb3b5e1ce'
down_revision: Union[str, Sequence[str], None] = 'fc460caa15a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.String(length=128), nullable=True),
    sa.Column('topic_key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('top_words', sa.JSON(), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'topic_key', name='uq_topics_run_topic_key')
    )
    op.create_index(op.f('ix_topics_org_id'), 'topics', ['org_id'], unique=False)
    op.create_index(op.f('ix_topics_run_id'), 'topics', ['run_id'], unique=False)
    op.create_index(op.f('ix_topics_team_id'), 'topics', ['team_id'], unique=False)
    op.create_index(op.f('ix_topics_topic_key'), 'topics', ['topic_key'], unique=False)
    op.create_table('document_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'document_id', name='uq_document_topics_run_document')
    )
    op.create_index(op.f('ix_document_topics_document_id'), 'document_topics', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_topics_run_id'), 'document_topics', ['run_id'], unique=False)
    op.create_index(op.f('ix_document_topics_topic_id'), 'document_topics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_topics_topic_id'), table_name='document_topics')
    op.drop_index(op.f('ix_document_topics_run_id'), table_name='document_topics')
    op.drop_index(op.f('ix_document_topics_document_id'), table_name='document_topics')
    op.drop_table('document_topics')
    op.drop_index(op.f('ix_topics_topic_key'), table_name='topics')
    op.drop_index(op.f('ix_topics_team_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_run_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_org_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
