"""init tables

Revision ID: c15daebc3c09
Revises: 
Create Date: 2026-02-22 00:12:13.665143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15daebc3c09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    op.create_table('inference_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_runs_model_name'), 'inference_runs', ['model_name'], unique=False)
    op.create_index(op.f('ix_inference_runs_status'), 'inference_runs', ['status'], unique=False)
    op.create_table('document_inference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('inference_run_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inference_run_id'], ['inference_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_inference_document_id'), 'document_inference', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_inference_inference_run_id'), 'document_inference', ['inference_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_inference_inference_run_id'), table_name='document_inference')
    op.drop_index(op.f('ix_document_inference_document_id'), table_name='document_inference')
    op.drop_table('document_inference')
    op.drop_index(op.f('ix_inference_runs_status'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_model_name'), table_name='inference_runs')
    op.drop_table('inference_runs')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
