"""add aggregation tables

Revision ID: e4ce2024e449
Revises: b32eb3b5e1ce
Create Date: 2026-02-22 01:03:15.481844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ce2024e449'
down_revision: Union[str, Sequence[str], None] = 'b32eb3b5e1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_channel'), 'alerts', ['channel'], unique=False)
    op.create_index(op.f('ix_alerts_day'), 'alerts', ['day'], unique=False)
    op.create_index('ix_alerts_day_org_team_type', 'alerts', ['day', 'org_id', 'team_id', 'alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_org_id'), 'alerts', ['org_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_team_id'), 'alerts', ['team_id'], unique=False)
    op.create_table('emotion_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'org_id', 'team_id', 'channel', 'source', 'sentiment', 'emotion', name='uq_emotion_daily_segment')
    )
    op.create_index(op.f('ix_emotion_daily_channel'), 'emotion_daily', ['channel'], unique=False)
    op.create_index(op.f('ix_emotion_daily_day'), 'emotion_daily', ['day'], unique=False)
    op.create_index('ix_emotion_daily_day_org_team', 'emotion_daily', ['day', 'org_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_emotion_daily_emotion'), 'emotion_daily', ['emotion'], unique=False)
    op.create_index(op.f('ix_emotion_daily_org_id'), 'emotion_daily', ['org_id'], unique=False)
    op.create_index(op.f('ix_emotion_daily_sentiment'), 'emotion_daily', ['sentiment'], unique=False)
    op.create_index(op.f('ix_emotion_daily_source'), 'emotion_daily', ['source'], unique=False)
    op.create_index(op.f('ix_emotion_daily_team_id'), 'emotion_daily', ['team_id'], unique=False)
    op.create_table('emotion_rolling',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('as_of_day', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of_day', 'window_days', 'org_id', 'team_id', 'channel', 'source', 'sentiment', 'emotion', name='uq_emotion_rolling_segment')
    )
    op.create_index(op.f('ix_emotion_rolling_as_of_day'), 'emotion_rolling', ['as_of_day'], unique=False)
    op.create_index('ix_emotion_rolling_asof_org_team', 'emotion_rolling', ['as_of_day', 'org_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_channel'), 'emotion_rolling', ['channel'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_emotion'), 'emotion_rolling', ['emotion'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_org_id'), 'emotion_rolling', ['org_id'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_sentiment'), 'emotion_rolling', ['sentiment'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_source'), 'emotion_rolling', ['source'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_team_id'), 'emotion_rolling', ['team_id'], unique=False)
    op.create_index(op.f('ix_emotion_rolling_window_days'), 'emotion_rolling', ['window_days'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_rolling_window_days'), table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_team_id'), table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_source'), table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_sentiment'), table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_org_id'), table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_emotion'), table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_channel'), table_name='emotion_rolling')
    op.drop_index('ix_emotion_rolling_asof_org_team', table_name='emotion_rolling')
    op.drop_index(op.f('ix_emotion_rolling_as_of_day'), table_name='emotion_rolling')
    op.drop_table('emotion_rolling')
    op.drop_index(op.f('ix_emotion_daily_team_id'), table_name='emotion_daily')
    op.drop_index(op.f('ix_emotion_daily_source'), table_name='emotion_daily')
    op.drop_index(op.f('ix_emotion_daily_sentiment'), table_name='emotion_daily')
    op.drop_index(op.f('ix_emotion_daily_org_id'), table_name='emotion_daily')
    op.drop_index(op.f('ix_emotion_daily_emotion'), table_name='emotion_daily')
    op.drop_index('ix_emotion_daily_day_org_team', table_name='emotion_daily')
    op.drop_index(op.f('ix_emotion_daily_day'), table_name='emotion_daily')
    op.drop_index(op.f('ix_emotion_daily_channel'), table_name='emotion_daily')
    op.drop_table('emotion_daily')
    op.drop_index(op.f('ix_alerts_team_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_org_id'), table_name='alerts')
    op.drop_index('ix_alerts_day_org_team_type', table_name='alerts')
    op.drop_index(op.f('ix_alerts_day'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_channel'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
