"""add document ingestion fields

Revision ID: fcc54c501383
Revises: c15daebc3c09
Create Date: 2026-02-22 00:15:05.419755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc54c501383'
down_revision: Union[str, Sequence[str], None] = 'c15daebc3c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('org_id', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('team_id', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('source', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('channel', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('text_redacted', sa.Text(), nullable=False))
    op.add_column('documents', sa.Column('redaction_summary', sa.JSON(), nullable=False))
    op.add_column('documents', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_channel'), 'documents', ['channel'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index(op.f('ix_documents_team_id'), 'documents', ['team_id'], unique=False)
    op.create_index(op.f('ix_documents_timestamp'), 'documents', ['timestamp'], unique=False)
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_timestamp'), table_name='documents')
    op.drop_index(op.f('ix_documents_team_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_channel'), table_name='documents')
    op.drop_column('documents', 'timestamp')
    op.drop_column('documents', 'redaction_summary')
    op.drop_column('documents', 'text_redacted')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'channel')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'team_id')
    op.drop_column('documents', 'org_id')
    # ### end Alembic commands ###
